@CommandsService_HostAddress = http://localhost:5068

###
GET {{CommandsService_HostAddress}}/api/c/Platforms/
Accept: application/json

###
POST {{CommandsService_HostAddress}}/api/c/Platforms/
Accept: application/json


@CommandsService_DockerHostAddress = http://localhost:8080
###
GET {{CommandsService_DockerHostAddress}}/api/c/Platforms/
Accept: application/json
